# Numpy

Numpy é um pacote amplamente conhecido em Python para ciência de dados. Este pacote facilita a manipulação e os cálculos com vetores e matrizes. Seu elemento estrutural mais importante é o np.array que funciona como um veetor onde se armezena os valores.

## Usando o pacote Numpy

In [1]:
import numpy as np

Para criar um np.array, basta chamar a função np.array() e passar uma lista como parâmetro.

In [2]:
lista1 = [1, 2, 3]

np_array1 = np.array(lista1)
np_array1

array([1, 2, 3])

Numpy também aceita uma lista de strings como parâmetro e cria o np.array. Entretanto, neste caso não é possível usar as funções matemáticas do pacote.

In [3]:
lista2 = ['a', 'b', 'c']

np_array2 = np.array(lista2)
np_array2

array(['a', 'b', 'c'], dtype='<U1')

Numpy possui algumas funções matemáticas já implementadas que deixam seu uso mais simples

In [4]:
np_array1.sum()

6

Como inidicado anteriormente, não é possível aplicar as funções aos np.arrays com strings.

In [5]:
np_array2.sum()

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [6]:
np_array1.mean()

2.0

In [7]:
np_array1.max()

3

In [8]:
np_array1.min()

1

In [9]:
np_array1.std()

0.816496580927726

Os np.arrays também podem aceitar os operadores aritméticos (+, -, *, /).

É possível realizar as operações com escalares (números) ou vetores (np.arrays).

In [10]:
%%timeit
my_list = [1, 2, 3]

for i in range(3):
    my_list[i] += 1

530 ns ± 220 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
%%timeit
my_arr = np.array([1, 2, 3])

for i in range(3):
    my_arr[i] += 1

1.77 µs ± 724 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
np_array1 + 1

array([2, 3, 4])

In [13]:
np_array1 - 2

array([-1,  0,  1])

In [14]:
np_array1 * 2

array([2, 4, 6])

In [15]:
np_array1 / 2

array([0.5, 1. , 1.5])

É importante ter em conta que para as operações funcionarem, os dois np.arrays devem ter o mesmo número de elementos e formato de dados. O Atributo ``shape`` pode ser utilizado para verificar o formato.

In [16]:
# a função np.ones_like cria um novo np.array com o mesmo formato do np.array passado como parâmetro, com o valor 1 em todas as posições
np_array2 = np.ones_like(np_array1)
np_array2

array([1, 1, 1])

In [17]:
np_array1.shape

(3,)

In [18]:
np_array2.shape

(3,)

In [19]:
np_array1.shape == np_array2.shape

True

In [20]:
np_array1 + np_array2

array([2, 3, 4])

In [21]:
np_array1 + np.array([3, 4, 5])

array([4, 6, 8])

In [22]:
np_array1 - np.array([3, 4, 5])

array([-2, -2, -2])

In [23]:
np_array1 * np.array([3, 4, 5])

array([ 3,  8, 15])

In [24]:
np_array1 / np.array([3, 4, 5])

array([0.33333333, 0.5       , 0.6       ])